# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ben Reeves
author: Ben Reeves
email: bgreeves@umich.edu
description: >- # this means to ignore newlines until "baseurl:"
  Software engineer, musician, designer, builder, and lifelong goofball.
  This is my personal website. Here you'll find my blog where
  I write about my hobbies, and links to other pages of mine.
url: "https://renbeeves.com" # the base hostname & protocol for your site, e.g. http://example.com

# Social
linkedin_username: ben-reeves
github_username:  bgr360

# Posts
show_excerpts: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - .gitignore
  - CNAME
  - README.md
